import './globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Suspense } from 'react'

import { RootProvider } from '@/shared/providers/root.provider'

import { Loading } from '@/components'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang='ru'
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            suppressHydrationWarning
        >
            <body className='min-h-screen w-full min-w-dvw'>
                <Suspense fallback={<Loading className='h-dvh w-dvw' />}>
                    <RootProvider>{children}</RootProvider>
                </Suspense>
            </body>
        </html>
    )
}
